### ISSUE TITLE
String Index OOB in endpoint with no params. 

### ISSUE THREAD

**Issue by adetlefsen-rms** [AresS31/swurg#14]
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967)
	at burp.Helper.parseParams(Helper.java:65)
```

Comes from here where you are trying to remove the final comma: 

https://github.com/AresS31/swurg/blob/master/burp/Helper.java#L65

But if there is no parameter, the string length is zero.

**Comment by AresS31** [comment]
I am not sure that issue comes from here because before doing the operation removing the final coma there is a check to ensure that the params are not empty `if (params != null)`.

Moreover, I am able to parse swaggers containing empty parameters with no issue.

Could you please provide more information? Ideally (if possible) send me the swagger file that you are trying to parse on an email. That would help me troubleshoting that issue.

**Comment by adetlefsen-rms** [comment]
Example swagger file that causes the error: 

```
{
  "swagger": "2.0",
  "info": {},
  "host": "some.server.com:20666",
  "basePath": "/http://some.server.com:20666",
  "tags": [
    {
      "name": "analysis"
    },
    {
      "name": "generic"
    }
  ],
  "schemes": [
    "http"
  ],
  "paths": {
    "/": {
      "get": {
        "operationId": "get",
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "string"
            },
            "headers": {}
          }
        }
      }
    }
  }
}
```

**Comment by AresS31** [comment]
Thanks, I am going to have a look at this tomorrow. But at first, I would say that that removing that line:
` "parameters": [],` could solve the issue since I suspect the List<Parameter> params to contain an empty `Parameter ` instead of `null`.
Alex

**Comment by AresS31** [comment]
The target website still has to have a valid swagger definition!

That's the prerequisite for the plugin to work, swurg does not have to validate the swagger definition; there is already plenty of websites available for that.
As I already said, I will have a look at the issue and IF it is an exception not-handled by swurg I will fix it, otherwise you will have to obtain a properly formatted swagger file! 

Swurg is not a bug free plugin and all reported issues are appreciated when properly documented. 

This is an on-going project (cf. readme.md) and finding issues is quite normal.

/Alex

**Comment by adetlefsen-rms** [comment]
It is perfectly valid for `parameters` to be an empty array in the swagger definition. 

Understood that this is an on-going project and that your valuable time goes into it. I appreciate it.
