### ISSUE TITLE
Feature request include POST body

### ISSUE THREAD

**Issue by luh2** [AresS31/swurg#49]
Hi,

When I parse a swagger file, the creation of the request works fine. 

Many swagger files I have parsed lately include examples of what is expected as body in POST requests. It would be nice to take this example value instead of `body=fuzzMe`.

**Comment by AresS31** [comment]
Hi @luh2,

The previous version of Swurg had this feature. However, I decided to re-write the plugin from scratch to make a more extensive use of the Burp libraries and to in order to use the Java Swagger library (delegating the maintenance work to this library rather than maintaining my own implementation of it).

The only caveat with this official Java swagger library is that there is no option to get the type of parameter expected, please see my following issue on their GitHub repository.

https://github.com/swagger-api/swagger-core/issues/2601

Hope this helps you to understand the issue.

Kind regards,
Alex

**Comment by luh2** [comment]
Unfortunately makes sense. Thanks for the quick reply.

**Comment by AresS31** [comment]
@luh2 this issue has been solved in the last commit. Now the expected type is explicit in the request parameters.
