### ISSUE TITLE
Possibility for loose parsing

### ISSUE THREAD

**Issue by drwetter** [aress31/swurg#70]
Hi,

thanks for the tool which I am using in burp!

I am all in for being compliant with open standards. However as the tool should assist in testing I would personally find it better if the specification is not met it won't be a hard failure. Or at least if there would be a possibility to override swurg being strict.

In my case the scheme declaration was missing, see ``src/main/java/swurg/process/Loader.java``,(git blame is telling me that it was changed in f592a287)

Cheers, Dirk

**Comment by drwetter** [comment]
PS: of course in most of the cases one can edit the json before.

**Comment by drwetter** [comment]
As fa as the schemes are concerned the error message ``"The OpenAPI specification contained in %s is missing the mandatory field: 'schemes'", `` seems [wrong](https://swagger.io/docs/specification/2-0/api-host-and-base-path/l): _If schemes are not specified, the scheme used to serve the API specification will be used for API calls_

**Comment by aress31** [comment]
Hi @drwetter thanks for opening the ticket, this version of Swurg is a bit old and I haven't had the time to get a proper look at it to update and improve it owing to other commitment at the minute.

At the time I wrote this plugin, the `scheme` field was iirc mandatory and the point of Swurg was not to validate Swagger files but to parse them, that would have been too much of an overhead to validate then parse, right now I am probably sure that the underlying library used but this extension could somehow assist with that.

What I suggest for the time being is for you to open a ticket directly at https://github.com/PortSwigger/openapi-parser so that the guys at PortSwigger can work on that.

**Comment by drwetter** [comment]
Thanks for the (honest) feedback. Actually it seems @PortSwigger 's version is even behind your version.  And for some reason their fork doesn't even has a button for "Issue". But maybe somebody's over there is reading this.

cc @pajswigger

**Comment by aress31** [comment]
@drwetter after finding some motivations, I refactored this project and it now support OAS up to 3.x, I squashed most of the bugs whilst I was on it, see if you spot anything, please don't hesitate to raise an issue! 😇
