### ISSUE TITLE
OpenAPI Parser

### ISSUE THREAD

**Issue by samvny68** [aress31/swurg#74]
Hi, hope you're doing good!!!

After the latest update from Burp the OpenAPI Parser is not working as expected. Before it used to.

When tried to import the swagger.json it gives an error. Cannot invoke "io.swagger.v3.oas.models.OpenAPI.getservers()" because "openAPI" is null. 

Trying to import the swagger version 2.0 file

Can you please let us know what we can do here?

Thanks in Advance

**Comment by Captain404** [comment]
![image](https://user-images.githubusercontent.com/58698256/152518347-2a6473a6-54f7-4690-ae76-bc5f4c432b85.png)
Same issue with me

**Comment by aress31** [comment]
@samvny68 could you please share the file with me for troubleshooting?

**Comment by aress31** [comment]
Samvny, without the file it will be hard for me to troubleshot, hit me up on ateyar@aegiscyber.co.uk if you don't want to share the file publically.

**Comment by falconws** [comment]
The same issue with me and can't share due to confidentiality.
I've tested openapi v3 yaml file.

> ![image](https://user-images.githubusercontent.com/58698256/152518347-2a6473a6-54f7-4690-ae76-bc5f4c432b85.png) Same issue with me

**Comment by aress31** [comment]
@falconws the message is clear, you need a server field.

**Comment by falconws** [comment]
> @falconws the message is clear, you need a server field.

My openapi.yaml file is

```
openapi: 3.0.0
info:
    ...omit
servers:
    - url: "..."
       description: ...
tags:
    - name: ...
    ... omit ...
```
So the `servers` field exists.

**Comment by yrjo** [comment]
same here, server field is there and the same issue as mentioned above,
openapi: 3.0.2
bupr: newest version pro, 2022.2.4 (the same for the version before)

**Comment by aress31** [comment]
@yrjo please follow the instructions on the doc and let me know if it works.

- https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by floyd-fuh** [comment]
@aress31  please read the error message again. It's not that "server" is null, but that "OpenAPI" is null. So the entire parsers does not seem to recognize it as a valid openapi file, so this must have been something bigger.  In the extender tab - errors we get:

```
swurg.process.Loader -> Input length = 1
swurg.gui.ParserPanel$LoadButtonListener -> Cannot invoke "io.swagger.v3.oas.models.OpenAPI.getServers()" because "openAPI" is null
```

When creating a local webserver quickly, sending the openapi yaml file through Burp and then sending the request/response via Context menu leads to:

```
burp.ContextMenuFactory -> Cannot invoke "String.equals(Object)" because the return value of "java.net.URI.getScheme()" is null
```

So I thought let's do some divide and conquer. I used the basic example from https://swagger.io/docs/specification/basic-structure/ as a "known good" state and then always copied over some parts of the yaml I wanted to test. Then it was a simple divide-and-conquer. Here's what I found out:

- I hate yaml
- YAML and unicode are no friends, just one example: https://stackoverflow.com/questions/45281596/dumping-unicode-with-yaml

I still don't even know if YAML supports unicode or not, so I also don't know if this extension has a bug or not, but here's what I did:

- Replace “ with nothing
- Replace – with -
- Get annoyed by manually finding unicode characters and use `grep --color='auto' -P -n "[\x80-\xFF]" openapi.yaml`
- Replace © with nothing
- Get annoyed that it still doesn't work because we now just get an exception `attribute paths.'/test'(post).requestBody.content.'application/json;charset=utf-8'.schema.#/testing/Create is missing` instead of the original one
- Give up

**Comment by aress31** [comment]
@floyd-fuh could you please pull the latest version and try again to check if #81 and [4d53ce7](https://github.com/aress31/swurg/commit/4d53ce7877c3fbd815f28738cff6e6df74476eab) fixed the issue?

**Comment by aress31** [comment]
https://github.com/aress31/swurg/commit/044ac747e10d5e19d18f50a00583bc16b37440e1
